export type SeedCategory = { name: string; tasks: string[] };

export const seedTasks: SeedCategory[] = [
  {
    name: "Opening",
    tasks: [
      "Stock the grab and go cooler with soda",
      "Make sure condiments and to go backs are ready for customers",
      "Make sure cups and lids are restocked",
      "Trash cans have liners and placed in appropriate areas",
      "Trash removed",
      "Area Swept",
      "Area Mopped",
      "Tables cleaned off and wiped down",
      "Tables straightened",
      "Chairs straightened",
      "Tighten loose tables",
      "Turn on all fryers",
      "Turn on Toaster Oven",
      "Make sure all knobs and locking nuts are tightened on source pumps",
      "Double check source containers to see if they need to be switched out",
      "Make sure all utensils and small wares are in their correct spot",
      "To Go Boxes Restocked",
      "Restock list for storage filled out for utiliity",
      "Wipe down ordering screens",
      "Trash and cardboard taken to Dumpster",
      "Count Safe and registers",
      "Send safe count and registers count to managers email",
      "Grab towels and approns from downstairs",
      "Complete restock list from downstairs",
    ],
  },
  {
    name: "Closing",
    tasks: [
      "Take off backing and liquid catcher, wash in back",
      "Nozzels removed and soaked for 15 min",
      "Restock cups, lids, forks, wet naps, ketchup",
      "Trash removed",
      "Dessert baskets placed on the back counter",
      "All grab and go bottles removed and placed in the cooler",
      "Area Swept",
      "Area Mopped",
      "Tables cleaned off and wiped down",
      "Tables straightened",
      "Chairs straightened",
      "Tighten loose tables",
      "Wipe down all sauce pumps, handles, boxes",
      "Make sure all knobs and locking nuts are tightened on source pumps",
      "Plastic Wrap Sauce Pumps and Bottles",
      "Sauce backups are restocked",
      "Clean out fryers and filter all",
      "Make sure all utenzils and small wares are placed back for morning crew",
      "Stainless steel walls wiped down",
      "All tables and equipment pulled away from walls, floors sweeped and mopped",
      "Change Oil (When needed)",
      "Wipe inside of all Staition coolers on the line",
      "All trash taken out, new bags placed in",
      "Hood Vents are cleaned (4 to the right)",
      "Mop sink is cleaned",
      "Dust pan washed out",
      "All cash drops entered into SBO",
      "Safe and cash register counts",
      "Email safe, cash register counts and cash overage/shortage to managers",
    ],
  },
];
